# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"count_parameters": "3. Model design.ipynb",
         "DanQ": "3. Model design.ipynb",
         "ConvBN": "3. Model design.ipynb",
         "SEblock": "3. Model design.ipynb",
         "ResBlock1D": "3. Model design.ipynb",
         "Resnet1D": "3. Model design.ipynb",
         "BiLSTM": "3. Model design.ipynb",
         "BERT": "3. Model design.ipynb",
         "TransXL": "3. Model design.ipynb",
         "ClsfHead": "3. Model design.ipynb",
         "ResSeqLin": "3. Model design.ipynb"}

modules = ["models.py"]

doc_url = "https://Rvbens.github.io/lib/"

git_url = "https://github.com/Rvbens/lib/tree/master/"

def custom_doc_links(name): return None
